root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/pixelbeast ./src/cmd"
  bin = "./tmp/pixelbeast"
  args = []
  include_ext = ["go", "html", "css", "js"]
  exclude_ext = ["_test.go"]
  include_dir = ["src"]
  exclude_dir = ["tmp", "vendor", "testdata", "sites", "ftp", "log", "docs", "config", "ssl", "backups"]
  delay = 1000
  stop_on_root = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
